color: null
fieldLayouts:
  73b5153c-df44-47fe-80e2-4af28195d4de:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-20T01:38:11+00:00'
            elementCondition: null
            fieldUid: 9c7052fe-6ae0-4dc9-b800-6447324e9ca6 # Body Image
            handle: imageGallery
            includeInCards: false
            instructions: null
            label: 'Image Gallery'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62bbe082-a074-4f51-8737-67de89be7d8e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-20T01:38:11+00:00'
            elementCondition: null
            fieldUid: dde45219-4f2c-4aab-b99c-e4e0dd36e4ef # Option Gallery
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b21ca4c-f2e5-401d-9542-4b56ca270800
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d422f1f4-b157-457b-9e94-c9028477e6bf
        userCondition: null
handle: layoutGallery
hasTitleField: false
icon: null
name: 'Layout Gallery'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
