color: null
fieldLayouts:
  b8db917f-6a74-414d-8d25-153eefc6105a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-19T08:38:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8e9132a4-7581-44f1-bc84-b94c316cae5c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-19T08:40:56+00:00'
            elementCondition: null
            fieldUid: e694772e-9370-41bc-98e7-5bea324a09e4 # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63c6bdd5-3b10-42b2-a476-cd06d73ebdb8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-19T08:40:56+00:00'
            elementCondition: null
            fieldUid: 9c7052fe-6ae0-4dc9-b800-6447324e9ca6 # Body Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11457d86-dc9e-4c4a-a6e1-7245bf3420ac
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-19T08:40:56+00:00'
            elementCondition: null
            fieldUid: 87836a9f-ae5f-4937-8a83-a06a2ac726ae # Body Editor
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 020a436e-41ff-46a2-8752-16f5ef612e19
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ee92b4de-31d6-487b-80bd-3845c3519bd5
        userCondition: null
handle: layoutPlatform
hasTitleField: true
icon: null
name: 'Layout Platform'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
