color: null
fieldLayouts:
  2e77b349-5c64-4461-a18f-d474e326c290:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-19T07:04:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9344e3bc-cb9a-435b-8749-6bb379a44a59
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-19T07:01:45+00:00'
            elementCondition: null
            fieldUid: 47ab6554-2c28-4a53-bb94-f62ffa323d2d # Nav Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3312be43-8e24-47f8-8a22-5f3aec4df2e4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6b0ac9f1-ceb4-4cf9-8b9d-06d55574b7d8
        userCondition: null
handle: navigasi
hasTitleField: true
icon: null
name: Navigasi
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
