color: null
fieldLayouts:
  66afc82d-5d36-455e-a5a4-0f92c1f4c12e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-20T02:40:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b685d26e-923e-4a7e-ba66-fec61534569e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-20T02:38:38+00:00'
            elementCondition: null
            fieldUid: e694772e-9370-41bc-98e7-5bea324a09e4 # Body
            handle: peopleName
            includeInCards: false
            instructions: null
            label: 'People Name'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 383e24df-4b59-44ec-9614-5245ba558846
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-20T02:38:38+00:00'
            elementCondition: null
            fieldUid: e694772e-9370-41bc-98e7-5bea324a09e4 # Body
            handle: peopleStatus
            includeInCards: false
            instructions: null
            label: 'People Status'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ca21f00-5ec7-40ac-8d07-0316a6036b5f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-20T02:38:38+00:00'
            elementCondition: null
            fieldUid: 9c7052fe-6ae0-4dc9-b800-6447324e9ca6 # Body Image
            handle: peopleImage
            includeInCards: false
            instructions: null
            label: 'People Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 250e07ce-3b56-4356-95e4-779182337a66
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 65981716-5648-4619-a3b6-7e2e659d57b2
        userCondition: null
handle: peoplePage
hasTitleField: true
icon: null
name: 'People Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
