baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'PT Multi Medika Mahadata'
primary: true
siteGroup: 0b56403c-5415-4fd5-a06f-3253b5ef1ff5 # PT Multi Medika Mahadata
sortOrder: 1
