columnSuffix: null
handle: bodyEditor
instructions: null
name: 'Body Editor'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 95eea75c-5184-442c-aa2b-a95999a7d093 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
