defaultPlacement: end
enableVersioning: true
entryTypes:
  - d98fc999-1654-41da-9d7a-4727e195ef96 # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  64e53b69-ab01-497f-a11b-5a0e1ec07062: # PT Multi Medika Mahadata
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
